# Generated by Django 4.2.7 on 2025-09-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('trimester', models.CharField(max_length=50, verbose_name='Trimester')),
                ('class_name', models.CharField(max_length=100, verbose_name='Class')),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic')], default='fr', max_length=2, verbose_name='Language')),
                ('total_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Average')),
                ('class_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Class Rank')),
                ('level_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Level Rank')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='Total Days')),
                ('present_days', models.PositiveIntegerField(default=0, verbose_name='Present Days')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='Absent Days')),
                ('attendance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Attendance Rate')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Teacher Notes')),
                ('principal_notes', models.TextField(blank=True, verbose_name='Principal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bulletin', 'Bulletin Scolaire'), ('attestation_presence', 'Attestation de Présence'), ('attestation_inscription', "Attestation d'Inscription"), ('receipt', 'Receipt'), ('other', 'Other')], max_length=30, verbose_name='Document Type')),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic')], default='fr', max_length=2, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('file_path', models.CharField(max_length=500, verbose_name='File Path')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='BulletinSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('subject_name_ar', models.CharField(blank=True, max_length=100, verbose_name='Subject Name (Arabic)')),
                ('coefficient', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Coefficient')),
                ('average', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average')),
                ('teacher_name', models.CharField(blank=True, max_length=100, verbose_name='Teacher Name')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Teacher Notes')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='documents.bulletin')),
            ],
            options={
                'verbose_name': 'Bulletin Subject',
                'verbose_name_plural': 'Bulletin Subjects',
                'ordering': ['subject_name'],
            },
        ),
        migrations.AddField(
            model_name='bulletin',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin', to='documents.document'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='accounts.student'),
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation_type', models.CharField(choices=[('presence', 'Attestation de Présence'), ('inscription', "Attestation d'Inscription")], max_length=20, verbose_name='Attestation Type')),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic')], default='fr', max_length=2, verbose_name='Language')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('class_name', models.CharField(max_length=100, verbose_name='Class')),
                ('level_name', models.CharField(max_length=100, verbose_name='Level')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='documents.document')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
                'ordering': ['-created_at'],
            },
        ),
    ]
